### ISSUE TITLE
Doesn't preserve directory structure

### ISSUE THREAD

**Issue by tomekwi** [sindresorhus/gulp-tar#14]
Hi, it seems that running `gulp.src("package/**").tar("package.tar")` over this tree:

```
package
|-- a-file
`-- directory
    `-- nested-file
```

…results in:

```
package.tar
|-- a-file
`-- nested-file
```

I can't find a way to preserve the structure, like so:

```
package.tar
|-- a-file
`-- directory
    `-- nested-file
```

**Comment by tomekwi** [comment]
Sorry, false alarm. I seem to be doing something wrong.

**Comment by flying-sheep** [comment]
since you are DenverCoder9 and me cueball:

![](http://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

here the answer:

[`gulp.src(..., { base: '.' })`](https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsbase)

**Comment by tomekwi** [comment]
:D wow, thanks! Who would have thought...

**Comment by tomekwi** [comment]
By the way – just for the record:

I wanted to use gulp-tar to manually pack an npm package – a bit like reinventing the wheel in fact. So though npm itself isn't particularly nice to work with programatically, I ended up using it: https://docs.npmjs.com/api/pack .
