### ISSUE TITLE
[Feature Request] Add Exclude options to gulp-tar

### ISSUE THREAD

**Issue by toni-moreno** [sindresorhus/gulp-tar#18]
could be interesting if added this option. Similar what --exclude= or --exclude-from-file does in the GNU tar command.

https://www.gnu.org/software/tar/manual/html_section/tar_49.html

Thank you very much

**Comment by sindresorhus** [comment]
Just exclude the files using a glob pattern in `gulp.src` or use `gulp-filter` before using this plugin, or something similar. That's the gulp way. Gulp plugins just accept files and do something with them. Imagine if every gulp plugin has to manually implement an exclude option.
