### ISSUE TITLE
execution fails if not using vinyl-fs on gulp 3.x

### ISSUE THREAD

**Issue by Blaimi** [sindresorhus/gulp-tar#28]
```
node_modules/gulp-tar/index.js:28
		if (file.isSymbolic()) {
		         ^

TypeError: file.isSymbolic is not a function
```

**Comment by sindresorhus** [comment]
Gulp v3 is not supported: https://github.com/sindresorhus/gulp-tar/blob/4a142e43ea8512d94ec75bc29cd589b7dd748d95/package.json#L51

**Comment by Blaimi** [comment]
yes, but it's only a peer-dependency ;)

It's up to you if you want to merge or close without merging https://github.com/sindresorhus/gulp-tar/pull/29. A solution is using vinyl-fs.src instead of gulp.src. Even with `resolveSymlinks: true` (default) the isSymbolic() is implemented.

**Comment by sindresorhus** [comment]
> yes, but it's only a peer-dependency ;)

The whole point of peer dependencies is to define that something works with a certain package without having to depend on it.
